[package]
name = "rs"
version = "0.1.0"
authors = ["wenchao.guo <wenchao.guo@wz-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
